# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{raf}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["garin"]
  s.date = %q{2011-04-07}
  s.description = %q{raf is simple document format}
  s.email = %q{garin54@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "test/helper.rb"
  ]
  s.homepage = %q{http://github.com/garin/raf}
  s.licenses = ["GPL"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{raf is simple document format}
  s.test_files = [
    "test/helper.rb",
    "test/test_descblock.rb",
    "test/test_emphasis.rb",
    "test/test_erb.rb",
    "test/test_footnote.rb",
    "test/test_headline.rb",
    "test/test_headline_and_itemlist.rb",
    "test/test_helper.rb",
    "test/test_image.rb",
    "test/test_italic.rb",
    "test/test_itemlistblock.rb",
    "test/test_numlistblock.rb",
    "test/test_paragraph.rb",
    "test/test_quoteblock.rb",
    "test/test_reference.rb",
    "test/test_ruby.rb",
    "test/test_strike.rb",
    "test/test_tableblock.rb",
    "test/test_verb.rb",
    "test/ts_block.rb",
    "test/ts_inline.rb",
    "test/ts_rafparser.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

